name: Upload Go test results

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: go get -v ./...

      - name: Test with Go
        run: go test -v ./...
